### ISSUE TITLE
traitlets >= 4.1 is required

### ISSUE THREAD

**Issue by jakevdp** [conda-forge/altair-feedstock#1]
For the next release, we should pin this in the recipe.
See https://github.com/ellisonbg/altair/issues/182

**Comment by SylvainCorlay** [comment]
You can add this requirement for the current version and increase the build number in the feedstock.

**Comment by jakevdp** [comment]
Understood – I was mainly noting this so I wouldn't forget!

**Comment by jakevdp** [comment]
Fixed in #3
