### ISSUE TITLE
CircleCI is run twice

### ISSUE THREAD

**Issue by isuruf** [conda-forge/altair-feedstock#7]
We had these issues long time ago when the feedstock was added twice. It seems this feedstock wasn't fixed.

cc @jakirkham

**Comment by jakirkham** [comment]
Thanks @isuruf. Normally what happens is an additional webhook gets added if the feedstock got stuck in the staged-recipes churn. The extra webhook is responsible for these duplicate builds. Fixing this sort of issue with AppVeyor is a bit of an "art" as it adds two projects as well. With CircleCI, there is only one project and multiple webhooks to it. So we just delete one of the extra webhooks, which is what I have done here.

Hopefully now that we are in a new era of staged-recipes in light of recent changes. Not to mention preventive maintenance done by some of the CIs (most notably AppVeyor). This should be less of an issue. Though it might be worth looking at making `conda-smithy` more robust to this too. ( https://github.com/conda-forge/conda-smithy/issues/444 )
