### ISSUE TITLE
ModuleNotFoundError after installing altair in conda environment

### ISSUE THREAD

**Issue by Jx-b** [conda-forge/altair-feedstock#8]
I just installed altair from conda-forge in a conda environment, I can see it in the list of installed packages when calling conda list:

```
(env) MacBook:~ xxx$ conda list
# packages in environment at /Users/xxx/miniconda3/envs/env:
#
altair                    1.2.1                      py_0    conda-forge
```

 but when I start python (or jupyterlab) and try to import it I get a ModuleNotFoundError. 

```
(env) MacBook:~ xxx$ python
Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:14:59) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import altair
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'altair'
```
Any idea of what might be wrong?

**Comment by jakevdp** [comment]
What's the output when you run the following at the terminal?
```
$ type python
```

**Comment by Jx-b** [comment]
I get this: 
```
(env) MacBook:~ xxx$ type python
python is /Users/xxx/miniconda3/envs/env/bin/python
```

**Comment by jakevdp** [comment]
I have no idea. I'd try starting over in a fresh environment. Something is strange on the conda side here.

**Comment by Jx-b** [comment]
It did not work with a new environment but it worked after updating conda to 4.5.0
